### ISSUE TITLE
Advanced semantic search

### ISSUE THREAD

**Issue by tschimbr** [eonum/drg-search#24]
Semantische Suche
Da die DRG-Texte nur eine bestimmte Bezeichnung eines medizinischen Sachverhalts enthalten und in der Sprache sehr technisch sind, ist eine Suche nur per DRG-Bezeichnung nicht optimal. Um die Suche einfacher zu machen, werden in der semantischen Suche gruppierungsrelevante ICD- und CHOP- Codes und ihre Bezeichnungstexte und Synonyme berücksichtigt. Der Benutzer kriegt von dieser Verknüpfung nichts mit. Jedoch ist so eine Suche über typische Behandlungen und Diagnosen einer DRG möglich. Synonyme bilden dabei auch die umgangssprachlichen Formen von Krankheitsbildern ab.

Inklusive Highlighting of search terms

**Comment by tschimbr** [comment]
Next steps:
1. Research search gem,
2. Integrate the gem and apply to standard texts
3. Ensure error tolerance
4. Highlight search terms
5. Integrate synonyms and relevant ICD / CHOP codes.

**Comment by asittampalam** [comment]
1.
Depends on how powerful it should be. I've read good things about ElasticSearch. It seems to have a quite modular design and allows things like adding your own tokenization steps etc. While it is designed for document based systems it can also index PostgreSQL databases. It exposes a REST-API but there is also a gem. I don't know if this is overkill but we might be able to use it for other medcode related things too.  What do you think?

**Comment by asittampalam** [comment]
searchkick might be a good gem to integrate ElasticSearch into rails.

**Comment by tschimbr** [comment]
See https://www.sitepoint.com/full-text-search-rails-elasticsearch/

**Comment by tschimbr** [comment]
Part 1-4 finished. See https://github.com/eonum/drg-search/tree/elasticsearch-with-searchkick

**Comment by tschimbr** [comment]
Maybe combine all code searches using inheritance (searchableCode), boost by aggregated N. Exclude Z DRGs in results.

**Comment by tschimbr** [comment]
Test multisearch for performance improvements:
https://github.com/ankane/searchkick#multi-search

**Comment by tschimbr** [comment]
For multisearch: First test all simple queries. If all of them are empty we search for complex queries.
