### ISSUE TITLE
Gather synonyms from MeSH

### ISSUE THREAD

**Issue by tschimbr** [eonum/drg-search#34]
See the file ETD.TXT in http://www.dimdi.de/dynamic/de/klassi/downloadcenter/mesh/mesh2016/mesh-2016-datenbankfassung.zip

Please also have a look at the French and Italian versions of MeSH if there are any.

In a second step we could include Wikipedia.

**Comment by tschimbr** [comment]
Use in elastic search: https://github.com/ankane/searchkick#synonyms
You can include all synonyms for all languages in the same file. This should do no harm.

**Comment by tschimbr** [comment]
You can put the data and an extraction script into the data repo.

**Comment by tschimbr** [comment]
I've tried to include the synonyms in searchkick but have not yet been successfull. There are also lots of single entities in synonyms.csv. Can you remove them.

**Comment by tschimbr** [comment]
Synonyms are now working. Please work on adding synonyms for IT and FR.

**Comment by asittampalam** [comment]
http://mesh.inserm.fr/mesh/ - If I'm understanding correctly we've to sign some sort of agreement in order to gain access to the french versionf of MeSH. Can I write them a mail?

**Comment by tschimbr** [comment]
Yes. What do we have to agree?

**Comment by asittampalam** [comment]
"L'Inserm met à votre disposition le fichier du MeSH bilingue sous format XML, sous réserve de signature d'une convention de concession de droit d'utilisation" - I think some sort of usage agreement. I'll write them in English and see how their reaction is.

**Comment by asittampalam** [comment]
In italian I've found https://w3.iss.it/site/Mesh - but nothing in a downloadable format yet...
